POST http://localhost:9000/singleTextGranularitySplit
Content-Type: application/x-www-form-urlencoded

originText="房间装修简约清时尚，整体布置成公主房风格，住进去能够享受到国王与公主般的待遇，充满着浪漫主义人文情怀。温馨舒适、干净舒心，阳台有配桌椅、可欣赏美丽夜景。有独立厨房，平时有时间还可以米西米西。 位于福州大学城，有着“闽侯东街口”的美称。周边有：博仕后时代购物广场，燕林国际影城，永嘉天地商城，永辉超市、升辉超市、建设银行、半天妖烤鱼、麦当劳以及美食城等。公交车有：55路、39路、41路、55路、95路、96路、150路、168路、330路、506路、528路、学区专线等，因此交通购物非常方便。 楼宇内安装三部电梯，楼道干净整洁。小区内绿树环抱、清新怡人，在这里您不用担心大都市的吵闹，安静的只有风吹树叶声。物业管理安全有序，24小时保安巡视，行人出入需刷门禁卡，让您住的安全放心。 生活不只是眼前的苟且， 还有诗和远方。岁月静好，时光不老，我们不散！"

###
